from collections.abc import Callable, Iterable, Iterator
from typing import overload

__all__ = ['CA', 'ca']

class CA[X]:
    def __init__(self, *xs: Iterable[X]) -> None: ...
    def __iter__(self) -> Iterator[X]: ...
    def __reversed__(self) -> Iterator[X]: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, idx: int) -> X: ...
    @overload
    def __getitem__(self, idx: slice) -> CA[X]: ...
    @overload
    def __setitem__(self, idx: int, vals: X) -> None: ...
    @overload
    def __setitem__(self, idx: slice, vals: Iterable[X]) -> None: ...
    @overload
    def __delitem__(self, idx: int) -> None: ...
    @overload
    def __delitem__(self, idx: slice) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def pushl(self, *xs: X) -> None: ...
    def pushr(self, *xs: X) -> None: ...
    def popl(self) -> X: ...
    def popr(self) -> X: ...
    def popld(self, default: X) -> X: ...
    def poprd(self, default: X) -> X: ...
    def poplt(self, maximum: int) -> tuple[X, ...]: ...
    def poprt(self, maximum: int) -> tuple[X, ...]: ...
    def rotl(self, n: int = 1) -> None: ...
    def rotr(self, n: int = 1) -> None: ...
    def map[Y](self, f: Callable[[X], Y]) -> CA[Y]: ...
    @overload
    def foldl[L](self, f: Callable[[X, X], X]) -> X: ...
    @overload
    def foldl[L](self, f: Callable[[L, X], L], start: L) -> L: ...
    @overload
    def foldr[R](self, f: Callable[[X, X], X]) -> X: ...
    @overload
    def foldr[R](self, f: Callable[[X, R], R], start: R) -> R: ...
    def capacity(self) -> int: ...
    def empty(self) -> None: ...
    def fraction_filled(self) -> float: ...
    def resize(self, minimum_capacity: int = 2) -> None: ...

def ca[T](*ts: T) -> CA[T]: ...
