from collections.abc import Callable, Iterable, Iterator
from typing import overload

__all__ = ['CAF', 'caf']

class CAF[X]:
    def __init__(self, *xs: Iterable[X], cap: int = 2) -> None: ...
    def __iter__(self) -> Iterator[X]: ...
    def __reversed__(self) -> Iterator[X]: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> X: ...
    def __setitem__(self, idx: int, val: X) -> None: ...
    def __delitem__(self, idx: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def pushl(self, item: X) -> None: ...
    def pushr(self, item: X) -> None: ...
    def popl(self) -> X: ...
    def popr(self) -> X: ...
    def popld(self, default: X) -> X: ...
    def poprd(self, default: X) -> X: ...
    def poplt(self, maximum: int) -> tuple[X, ...]: ...
    def poprt(self, maximum: int) -> tuple[X, ...]: ...
    def rotl(self, n: int = 1) -> None: ...
    def rotr(self, n: int = 1) -> None: ...
    def map[Y](self, f: Callable[[X], Y]) -> CAF[Y]: ...
    @overload
    def foldl[L](self, f: Callable[[X, X], X]) -> X: ...
    @overload
    def foldl[L](self, f: Callable[[L, X], L], start: L) -> L: ...
    @overload
    def foldr[R](self, f: Callable[[X, X], X]) -> X: ...
    @overload
    def foldr[R](self, f: Callable[[X, R], R], start: R) -> R: ...
    def capacity(self) -> int: ...
    def empty(self) -> None: ...
    def fraction_filled(self) -> float: ...

def caf[T](*ts: T, cap: int = 2) -> CAF[T]: ...
